# Change prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g default-terminal "screen-256color"

# Use Ctrl-arrow keys to switch panes
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

# Shift arrow to switch windows
bind S-h previous-window
bind S-l next-window

# Mouse mode
setw -g mouse on

# Set easier window split keys
bind-key v split-window -h
bind-key h split-window -v

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "~/.tmux.conf reloaded."

# Automatically set window title
setw -g automatic-rename

# pane border
set-option -g pane-border-style fg=colour235 #fg=base02
set-option -g pane-active-border-style fg=colour240 #fg=base01

# easier resizing
bind M-h resize-pane -L 10
bind M-j resize-pane -D 10
bind M-k resize-pane -U 10
bind M-l resize-pane -R 10

# close tmux if nothing is attached to it
set -g exit-unattached on

# This aint the military
setw -g clock-mode-style 12
