return {
  require ("plugins.fuzzy-search.keymaps.grep-dotfiles"),
  require ("plugins.fuzzy-search.keymaps.grep-notes"),
  require ("plugins.fuzzy-search.keymaps.open-file-browser"),
  require ("plugins.fuzzy-search.keymaps.search-builtin-pickers"),
  require ("plugins.fuzzy-search.keymaps.search-definitions"),
  require ("plugins.fuzzy-search.keymaps.search-diagnostics"),
  require ("plugins.fuzzy-search.keymaps.search-document-symbols"),
  require ("plugins.fuzzy-search.keymaps.search-dotfiles"),
  require ("plugins.fuzzy-search.keymaps.search-git-files"),
  require ("plugins.fuzzy-search.keymaps.search-implementations"),
  require ("plugins.fuzzy-search.keymaps.search-notes"),
  require ("plugins.fuzzy-search.keymaps.search-open-buffers"),
  require ("plugins.fuzzy-search.keymaps.search-references"),
  require ("plugins.fuzzy-search.keymaps.spell-check"),
}
